# Generated by Django 4.0.4 on 2022-05-27 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NumGroup',
            fields=[
                ('num_group', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('id_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TIS.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='TheorMat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theor_mat', models.CharField(max_length=200)),
                ('id_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TIS.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('login', models.CharField(max_length=50, verbose_name='Логин')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('num_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TIS.numgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('id_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TIS.topic')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_stud', models.CharField(max_length=200)),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TIS.question')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TIS.student')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TIS.question')),
            ],
        ),
    ]
