# Generated by Django 4.0.4 on 2022-06-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theormat',
            name='theor_mat',
            field=models.CharField(max_length=60000),
        ),
    ]
