# Generated by Django 4.0.4 on 2022-06-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIS', '0002_student_rating_student_rating_str'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='rating',
            new_name='best_rating',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='rating_str',
            new_name='best_rating_str',
        ),
        migrations.AddField(
            model_name='student',
            name='last_rating_str',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
